version: '3'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - djangonetwork

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 180951
    networks:
      - djangonetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - djangonetwork

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - djangonetwork

  ubuntu-client:
    image: ubuntu:latest
    command: tail -f /dev/null
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
