version: '3'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - djangonetwork

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 180951
    networks:
      - djangonetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
