version: '3'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 180951
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
